config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, only: [:sessions, :passwords]
  devise_for :admins, only: [:sessions, :passwords]
  devise_for :users, controllers: { :registrations => :registrations }

  resources :teams do
    resource :result
  end
  resources :charges

  namespace :customers do
    get 'my_teams' => 'my_teams#index'
  end

  get 'user/:id' => 'user#index', as: 'user_detail'
  get 'home' => 'pages#home'
  get 'player_news_nba' => 'leaderboard#player_news_nba'
  get 'jobs' => 'leaderboard#jobs'
  get 'pricing' => 'leaderboard#pricing'
  get 'faq' => 'leaderboard#faq'
  get 'leaderboard' => 'leaderboard#index'
  get 'leaderboard/profile/:id' => 'leaderboard#profile', as: 'leaderboard_profile'
  get 'nfl_leaderboard' => 'leaderboard#nfl_leaderboard'
  get 'mlb_leaderboard' => 'leaderboard#mlb_leaderboard'
  get 'soccer_leaderboard' => 'leaderboard#soccer_leaderboard'
  get 'march_madness_leaderboard' => 'leaderboard#march_madness_leaderboard'
  get 'nhl_leaderboard' => 'leaderboard#nhl_leaderboard'
  get 'strategy' => 'leaderboard#strategy'
  get 'livehelp' => 'leaderboard#livehelp'

  root 'pages#home'

  namespace :admin do
    resources :users
    resources :constant_values, only: [:edit, :update]
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def index
    @users = User.order(avarage_score: :desc)
  end

  def profile
    @user = User.find(params[:id])
  end
end

def nfl_leaderboard

end 


def jobs

end

def pricing

end  

def player_news_nba

end  

def faq

end  

def strategy

end  

def livehelp

end 

app/views/leaderboard/_profile.html.erb
<%= image_tag(@user.profile_image.url(:thumb), width: '100', border: '0', class: 'img-circle' ) if !@user.profile_image.nil? %>
<h3 class="media-heading"><%= @user.username %></h3>
<span><strong></strong></span>
<% @user.sport_list.each do |item| %>
  <span class="label label-default"><%= item %></span>
<% end %>
<span><strong></strong></span>
<% @user.favorite_team_list.each do |item| %>
  <span class="label label-default"><%= item %></span>
<% end %>
<hr>
<%= simple_format @user.bio %>
<%= link_to 'View Profile', user_detail_path(user), class: "btn btn-success" %>

app/views/leaderboard/faq.html.erb
<div class="container">
 
    <div class="row">
        <div class="col-sm-10 col-md-8 col-md-offset-1">
        <h1>FAQ</h1>
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                           Who is Fanalyst for?</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                           <p>Fanalyst is for eilite DFS players to show their skills and to build a following. It is also for people who want to improve their fantasy skills by learning from the best.</p>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">How do I become a Fanalyst?</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">Create an account and upload your teams. 
                            
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">What are the benefits of becoming a Fanalyst?</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                        <p>You can share your wealth of daily fantasy sports information, capitalizing on your love for sports.
                        </p>
                            
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">How do I increase my rank on the leaderboard?</a>
                        </h4>
                    </div>
                    <div id="collapseFour" class="panel-collapse collapse">
                        <div class="panel-body">
                       <p> The better you score, the more you earn with our performance based revenue share program. Promote yourself on FB, Insta, Twitter and other avenues to build your following and make more cash.</p>
                            
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">How do I create an account?</a>
                        </h4>
                    </div>
                    <div id="collapseFive" class="panel-collapse collapse">
                        <div class="panel-body">
                       <p> To create an account, you just need to create a username and password <%= link_to 'Sign Up', new_user_registration_path, class: "btn-danger btn-sm" %></p>
                            
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">How do I purchase a lineup?</a>
                        </h4>
                    </div>
                    <div id="collapseSix" class="panel-collapse collapse">
                        <div class="panel-body">
                       <p> Click Leaderboard, Discover Fanalysts by looking at their profiles, Click on ‘View lineups for today’ and enter in your credit card information to complete the purchase. You will receive an email receipt. 

All purchases are safely and securely handled through Stripe, a developer-friendly way to accept payments online!</p>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        </div>
    </div>
</div>

app/views/leaderboard/index.html.erb
<%= render '/shared/header' %>

<div class="container">

<% if user_signed_in? %>
<h4>1. Get started by setting up your profile, then upload your lineups for today <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-success" %></h4>

<h4>2. Once the games are over, go to  <%= link_to 'My teams', teams_path, class: "btn btn-primary" %> and click  "add results" to prove your score</h4>
<% end %>

<div class="col-md-12 col-sm-12 col-xs-12">

<div class="jumbotron">



<h1> NBA Leaderboard </h1>
</br>

 <p>
   <%= link_to 'NBA', leaderboard_path, class: "btn btn-success" %>
   <%= link_to 'NFL', nfl_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'MLB', mlb_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'Soccer', soccer_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'March Madness', march_madness_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'NHL', nhl_leaderboard_path, class: "btn btn-primary" %>
 </p>
 <h4>Fan Duel Median Score: <%= ConstantValue.first.fan_duel_median_score %></h4>

</div>

</div>
</div>


 <div class="col-md-12 col-sm-12 col-xs-12">
  <table class="table table-responsive table-striped">
  <tr>
  <th>Rank</th>
  <th></th>
  <th>Username</th>
  <th>Average Score</th>
  <th>+ / -</th>
  <th>Total Lineups Submitted</th>
  <th></th>
  </tr>
    <% @users.each_with_index do |user, index| -%>
      <tr>
        <td><h2><%= index + 1 %></h2></td>
        <td>
          <%= link_to leaderboard_profile_path(user), remote: true do %>
            <%= image_tag user.profile_image.url(:thumb), class: 'img-circle', width: '100' %>
          <% end %>
        </td>
        <td><%= user.username %></td>
        <td><%= user.avarage_score.round(1) %></td>
        <td><%= user.avarage_score.round(1) - ConstantValue.first.fan_duel_median_score.round(2)  %></td>
        <td><%= user.teams.joins(:result).count %></td>
        <td><%= link_to 'View Profile', user_detail_path(user), class: "btn btn-danger", data: { no_turbolink: true } %></td>
      </tr>
    <% end -%>
    </tbody>
  </table>
</div>
</div>



<div class="modal fade" id="dialog-form">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Fanalyst Info</h4>
      </div>
      <div id="profile" class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>

      <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60459974-1', 'auto');
  ga('send', 'pageview');

</script>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/leaderboard/jobs.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="box">
                <div class="box-icon">
                    <span class="fa fa-4x fa-laptop"></span>
                </div>
                <div class="info">
                    <h4 class="text-center">Part-Time (DFS) Daily Fantasy Sports Analyst </h4>
                    <p>Fanalyst Co brings together all the best daily fantasy sports players. If you have ever played daily fantasy sports before, you know that it takes a ton of research, following players, dedication, intuition, and strategy to do well to win money and make a decent return.

                    <p>As people trust investors with their hard earned cash to invest in the stock market, we have created a platform that allows you to win big money in the sports market by using our lineups created each and every day by our fanalysts. Our fanalysts have years of experience playing fantasy sports. They have a proven history of beating the market day after day, as they have a passion and insight for sports that only few people in this world come to score. </p>


                  <p>  Job Requirements:

                  <ul>
                  <li>Create lineups for fantasy sports exchanges such as Fanduel, DraftKings, Victiv, etc </li>
                  <li>Upload statistical, factual, and research content and or methods used to construct lineups </li>
                  <li>Establish a following of paid clients: The more clients you bring in, the more money you make  </li>
                  <li>Promote and engage your Fanalyst Profile 
                 <li>Showcase your fantasy sports skills on FB, Instagram and other social media to make even more money.  </li>

                    
                    </p>
                    <a href="" class="btn">Link</a>
                </div>
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="box">
              
                <div class="info">
                    <h4 class="text-center">Become a fanalyst</h4>
                    <p>Sign up and start uploading teams to prove your skills. The better you do, the more money you earn through our performance based revenue share program. </p>
                    <%= link_to 'Sign up',new_user_registration_path , class: "btn btn-success" %>
                </div>
            </div>

            <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60459974-1', 'auto');
  ga('send', 'pageview');

</script>
        </div>
  </div>
</div>

app/views/leaderboard/livehelp.html.erb
<div class="container">
<div class="jumbotron">



<h1> Live Fantasy Help</h1>
<h2>Text +1 770-282-9016 </h2>
</br>


</div>
</div>



<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60459974-1', 'auto');
  ga('send', 'pageview');

</script>

  
    
     <div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <div class="box">
                
                <div class="info">

                    
                    <p>Have a question about your lineup? Don't know who to start, shoot us a text. We can help.

                    

                    <p><%= link_to 'Text Us to Sign Up', new_user_registration_path, class: "btn btn-success", style: "margin-top:25px;" %></p>

                    
                   
                </div>
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
            <div class="box">
              


      <div class="row">
        <div class="col-md-12">
           <div class="box-icon">
                    <span class="fa fa-4x fa-comment"></span>
                </div>

         <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="box2">

              
                <div class="info">
                    <h4 class="text-center">Lineup Help</h4>
                    <h5 class="text-center">Davis or Cousins tonight? We do the research so you don't have to. </h5>
                    
                </div>
            </div>
          </div>


          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
             
            <div class="box2">

              
                <div class="info">
                    <h4 class="text-center">Strategy</h4>
                    
                    <h5 class="text-center"> A lot goes into a winning lineup. Ask us how you can develop a winning strategy. </h5>
                   
                </div>
            </div>
          </div>
          

          <div class="row">
          <div class="col-md-12">

          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="box2">
              
                <div class="info">
                    <h4 class="text-center">Injury Updates</h4>
                   
                    <h5 class="text-center"> We scour the internet to give you the most up to do date injury reports you request </h5>
                
                    
                </div>
            </div>
          </div>

         
          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="box2">
              
              
                <div class="info">
                    <h4 class="text-center">Projections</h4>
                  
                    <h5 class="text-center"> Ask us about a player and we will give you our projections using our algorithm.  

                                      </h5>
                                   
                    
                </div>
            </div>
          </div>

          

       </div>
        </div>
        </div>
 <div class="row">
          <div class="col-md-12">

          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="box2">
              
                <div class="info">
                    <h4 class="text-center">Late Night Scratches</h4>
                   
                    <h5 class="text-center"> Sick of losing because you didn't know Westbrook was not playing? We give you the latest player intel </h5>
                
                    
                </div>
            </div>
          </div>

         
          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="box2">
              
              
                <div class="info">
                    <h4 class="text-center">Hot List </h4>
                  
                    <h5 class="text-center"> Get a list of the hottest fantasy players the last 7 days
                      </h5>
                                   
                    
                </div>
            </div>
          </div>

          

       </div>
        </div>
        </div>

 <div class="row">
          <div class="col-md-12">

          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="box2">
              
                <div class="info">
                    <h4 class="text-center">Cold List</h4>
                   
                    <h5 class="text-center">We give you the list of people you can ruin your night </h5>
                
                    
                </div>
            </div>
          </div>

         
          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="box2">
              
              
                <div class="info">
                    <h4 class="text-center">Custom Player News</h4>
                  
                    <h5 class="text-center"> Stay in the know on the players you care about. 

                                      </h5>
                                   
                    
                </div>
            </div>
          </div>

          

       </div>
        </div>
        </div>
     

app/views/leaderboard/march_madness_leaderboard.html.erb
<div class="container2">
<div class="jumbotron">



<h2> March Madness Coming Soon! </h2>
</br>

 <p>
   <%= link_to 'NBA', leaderboard_path, class: "btn btn-success" %>
   <%= link_to 'NFL', nfl_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'MLB', mlb_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'Soccer', soccer_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'March Madness', march_madness_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'NHL', nhl_leaderboard_path, class: "btn btn-primary" %>
 </p>

</div>

</div>

  <div class="panel-default">
  <iframe width="196" height="135" src="https://www.onlinecountdowns.com/w/141024" frameborder="0"></iframe>
  </div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60459974-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/leaderboard/mlb_leaderboard.html.erb
<div class="container">
<div class="jumbotron3">



<h2> MLB Coming Soon! </h2>
</br>

 <p>
   <%= link_to 'NBA', leaderboard_path, class: "btn btn-success" %>
   <%= link_to 'NFL', nfl_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'MLB', mlb_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'Soccer', soccer_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'March Madness', march_madness_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'NHL', nhl_leaderboard_path, class: "btn btn-primary" %>
 </p>

</div>

</div>

  
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60459974-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/leaderboard/nfl_leaderboard.html.erb
<div class="container">
<div class="jumbotron2">



<h2> NFL Coming Soon! </h2>
</br>

 <p>
   <%= link_to 'NBA', leaderboard_path, class: "btn btn-success" %>
   <%= link_to 'NFL', nfl_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'MLB', mlb_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'Soccer', soccer_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'March Madness', march_madness_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'NHL', nhl_leaderboard_path, class: "btn btn-primary" %>
 </p>

 <div class="panel-default">
  <iframe width="196" height="135" src="https://www.onlinecountdowns.com/w/141024" frameborder="0"></iframe>
  </div>

</div>

</div>

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60459974-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/leaderboard/nhl_leaderboard.html.erb
<div class="container2">
<div class="jumbotron">



<h2> NHL Coming Soon! </h2>
</br>

 <p>
   <%= link_to 'NBA', leaderboard_path, class: "btn btn-success" %>
   <%= link_to 'NFL', nfl_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'MLB', mlb_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'Soccer', soccer_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'March Madness', march_madness_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'NHL', nhl_leaderboard_path, class: "btn btn-primary" %>
 </p>

</div>

</div>

  
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60459974-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/leaderboard/player_news_nba.html.erb
<div class="col-md-6 col-md-offset-3">

    <ul class="timeline">

       <li>
          <div class="timeline-badge success"><i class="glyphicon glyphicon-bell"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Reggie Jackson</h4>
              <p><small class="text-muted"> Jackson had a great game for pistons which is good to see since the Augustine trade. He had 25 points, 7 boards and 7 assists</small></p>
            </div>
            
          </div>

       <li>
          <div class="timeline-badge success"><i class="glyphicon glyphicon-bell"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Brandon Bass</h4>
              <p><small class="text-muted"> Bass had a huge game, grabbing 17 boards, 19 points, while adding 5 assists for a total of 41 fantasy points</small></p>
            </div>
            
          </div>


       <li>
          <div class="timeline-badge success"><i class="glyphicon glyphicon-bell"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Tony Parker</h4>
              <p><small class="text-muted"> Parker played one of his best games of the season Sunday, scoring a season-high 32 points (13-19 FG, 1-1 3Pt, 5-8 FT) to go with four rebounds and two assists in 30 minutes against Chicago.</small></p>
            </div>
            
          </div>

        <li>
          <div class="timeline-badge success"><i class="glyphicon glyphicon-bell"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Shaun Livingston</h4>
              <p><small class="text-muted"> Livingston recorded a season-high of 21 points (9-14 FG, 3-5 FT) during Sunday's win over the Clippers, to go along with eight rebounds, three assists and three steals in 28 minutes off the bench.</small></p>
            </div>
            
          </div>
        <li>
          <div class="timeline-badge success"><i class="glyphicon glyphicon-bell"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Devin Harris</h4>
              <p><small class="text-muted"> Devin Harris (hand) is listed as questionable for Sunday's game vs. the Lakers.
            X-rays came back clean on Harris' hand, but there was still enough discomfort for him to sit out vs. the Warriors on Friday. Harris has been a big part of the rotation for Dallas in recent games, and his absence would mean more minutes for Rajon Rondo and J.J. Barea.</small></p>
            </div>
            
          </div>
        </li>
        <li>
          <div class="timeline-badge success"><i class="glyphicon glyphicon-bell"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Jeremy Lin</h4>
            </div>
            <p><small class="text-muted">Jeremy Lin has been a new player since the All-Star break, averaging 15.5 points, 5.6 assists, 3.3 boards, 1.8 steals and 1.0 3-pointer over his last eight games.</small></p>
            
          </div>
        </li>
        <li>
          <div class="timeline-badge success"><i class="glyphicon glyphicon-bell"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Rajon Rondo</h4>
            </div>
             <p><small class="text-muted">Jeremy Lin has been a new player since the All-Star break, averaging 15.5 points, 5.6 assists, 3.3 boards, 1.8 steals and 1.0 3-pointer over his last eight games.</small></p>
            
              
            </div>
          </div>
        </li>
        
</div>

app/views/leaderboard/profile.js.erb
$('#profile').html("<%= escape_javascript(render partial: 'profile', locals: {user: @user}) %>");
$('#dialog-form').modal('show');

app/views/leaderboard/soccer_leaderboard.html.erb
<div class="container2">
<div class="jumbotron">



<h2> Soccer Coming Soon! </h2>
</br>

 <p>
   <%= link_to 'NBA', leaderboard_path, class: "btn btn-success" %>
   <%= link_to 'NFL', nfl_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'MLB', mlb_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'Soccer', soccer_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'March Madness', march_madness_leaderboard_path, class: "btn btn-primary" %>
   <%= link_to 'NHL', nhl_leaderboard_path, class: "btn btn-primary" %>
 </p>

</div>

</div>

 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60459974-1', 'auto');
  ga('send', 'pageview');

</script>