config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, only: [:sessions, :passwords]
  devise_for :admins, only: [:sessions, :passwords]
  devise_for :users, controllers: { :registrations => :registrations }

  resources :teams do
    resource :result
  end
  resources :charges

  namespace :customers do
    get 'my_teams' => 'my_teams#index'
  end

  get 'user/:id' => 'user#index', as: 'user_detail'
  get 'home' => 'pages#home'
  get 'player_news_nba' => 'leaderboard#player_news_nba'
  get 'jobs' => 'leaderboard#jobs'
  get 'pricing' => 'leaderboard#pricing'
  get 'faq' => 'leaderboard#faq'
  get 'leaderboard' => 'leaderboard#index'
  get 'leaderboard/profile/:id' => 'leaderboard#profile', as: 'leaderboard_profile'
  get 'nfl_leaderboard' => 'leaderboard#nfl_leaderboard'
  get 'mlb_leaderboard' => 'leaderboard#mlb_leaderboard'
  get 'soccer_leaderboard' => 'leaderboard#soccer_leaderboard'
  get 'march_madness_leaderboard' => 'leaderboard#march_madness_leaderboard'
  get 'nhl_leaderboard' => 'leaderboard#nhl_leaderboard'
  get 'strategy' => 'leaderboard#strategy'
  get 'livehelp' => 'leaderboard#livehelp'

  root 'pages#home'

  namespace :admin do
    resources :users
    resources :constant_values, only: [:edit, :update]
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('http://i.imgur.com/ueTdKJd.png', size: '55x50'), root_path, class: 'navbar-brand', style: 'margin-left: 5px; padding-top:0px;' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Leaderboard', leaderboard_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'My Lineups', teams_path %></li>
          <li><%= link_to 'Upload Lineup', new_team_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% elsif customer_signed_in? %>
          <li><%= link_to 'Teams', customers_my_teams_path %></li>
          <li><%= link_to 'Change Password', edit_customer_password_path %></li>
          <li><%= link_to 'Log out', destroy_customer_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>