config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, only: [:sessions, :passwords]
  devise_for :admins, only: [:sessions, :passwords]
  devise_for :users, controllers: { :registrations => :registrations }

  resources :teams do
    resource :result
  end
  resources :charges

  namespace :customers do
    get 'my_teams' => 'my_teams#index'
  end

  get 'user/:id' => 'user#index', as: 'user_detail'
  get 'home' => 'pages#home'
  get 'player_news_nba' => 'leaderboard#player_news_nba'
  get 'jobs' => 'leaderboard#jobs'
  get 'pricing' => 'leaderboard#pricing'
  get 'faq' => 'leaderboard#faq'
  get 'leaderboard' => 'leaderboard#index'
  get 'leaderboard/profile/:id' => 'leaderboard#profile', as: 'leaderboard_profile'
  get 'nfl_leaderboard' => 'leaderboard#nfl_leaderboard'
  get 'mlb_leaderboard' => 'leaderboard#mlb_leaderboard'
  get 'soccer_leaderboard' => 'leaderboard#soccer_leaderboard'
  get 'march_madness_leaderboard' => 'leaderboard#march_madness_leaderboard'
  get 'nhl_leaderboard' => 'leaderboard#nhl_leaderboard'
  get 'strategy' => 'leaderboard#strategy'
  get 'livehelp' => 'leaderboard#livehelp'

  root 'pages#home'

  namespace :admin do
    resources :users
    resources :constant_values, only: [:edit, :update]
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/result.rb
class Result < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :team

  validates :score, numericality: true
end

app/controllers/results_controller.rb
class ResultsController < ApplicationSignedInController
  def new
    @team = current_user.teams.find(params[:team_id])
    @result = @team.build_result
  end

  def create
    @team = current_user.teams.find(params[:team_id])

    # TODO: it would be interesting to have a background worker checking once a while if this results are correct
    respond_to do |format|
      if @team.create_or_update_result(result_params)
        format.html { redirect_to @team, notice: 'Result was successfully created.' }
      else
        @result = @team.result
        format.html { render :new }
      end
    end
  end

  def edit
    @team = current_user.teams.find(params[:team_id])
    @result = @team.result
  end

  def update
    @team = current_user.teams.find(params[:team_id])

    respond_to do |format|
      if @team.create_or_update_result(result_params)
        format.html { redirect_to @team, notice: 'Result was successfully updated.' }
      else
        @result = @team.result
        format.html { render :edit }
      end
    end

  end

  private

  def result_params
    params.require(:result).permit(:notes, :score, :image)
  end
end

app/views/results/_form.html.erb
<%= render '/shared/header' %>

<div class="container">
  <%= form_for @result, url: team_result_path(@team), html: {multipart: true} do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this team from being saved:</h2>

      <ul>
        <% @result.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="col-md-5 col-md-offset-3">
       
  <div class="box">
      <h1><%= @result.persisted? ? 'Update' : 'Add' %> result</h1>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control" %>
        <% if @result.image.exists? %>
          <img id="file" src="<%= @result.image.url %>">
        <% else %>
          <img id="file" src="#" alt="team image" style="display: none">
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :score %><br>
        <%= f.text_field :score, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :notes %><br>
        <%= f.text_area :notes, class: "form-control" %>
      </div>
      <div class="actions">
        <%= link_to 'Back', edit_team_path(@team), role: 'button', class: 'btn btn-primary' %>
        <%= f.submit @result.persisted? ? 'Update' : 'Add', class: "btn btn-danger" %>
      </div>
    </div>
  </div>

<% end %>
</div>

app/views/results/edit.html.erb
<%= render 'form' %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container2">

<h1>Listing Teams</h1>

</div>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= image_tag team.image.url(:thumb) %></td>
        <td><%= team.notes %></td>
        <td><%= team.score %></td>
        <td><%= team.user.email if team.user %></td>
        <td><%= link_to 'View Team', team , class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_team_path(team) %></td>
        <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team', new_team_path %>

app/views/results/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', teams_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container2">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Team</h4>

        <%= image_tag @record.image.url %>

        <p>
          <strong>Notes:</strong>
          <%= @record.notes %>
        </p>

        <%= link_to 'Edit', edit_team_path(@team) %> |
        <%= link_to 'Back', teams_path %>
      </div>
    </div>
  </div>
</div>