config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, only: [:sessions, :passwords]
  devise_for :admins, only: [:sessions, :passwords]
  devise_for :users, controllers: { :registrations => :registrations }

  resources :teams do
    resource :result
  end
  resources :charges

  namespace :customers do
    get 'my_teams' => 'my_teams#index'
  end

  get 'user/:id' => 'user#index', as: 'user_detail'
  get 'home' => 'pages#home'
  get 'player_news_nba' => 'leaderboard#player_news_nba'
  get 'jobs' => 'leaderboard#jobs'
  get 'pricing' => 'leaderboard#pricing'
  get 'faq' => 'leaderboard#faq'
  get 'leaderboard' => 'leaderboard#index'
  get 'leaderboard/profile/:id' => 'leaderboard#profile', as: 'leaderboard_profile'
  get 'nfl_leaderboard' => 'leaderboard#nfl_leaderboard'
  get 'mlb_leaderboard' => 'leaderboard#mlb_leaderboard'
  get 'soccer_leaderboard' => 'leaderboard#soccer_leaderboard'
  get 'march_madness_leaderboard' => 'leaderboard#march_madness_leaderboard'
  get 'nhl_leaderboard' => 'leaderboard#nhl_leaderboard'
  get 'strategy' => 'leaderboard#strategy'
  get 'livehelp' => 'leaderboard#livehelp'

  root 'pages#home'

  namespace :admin do
    resources :users
    resources :constant_values, only: [:edit, :update]
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("http://i.imgur.com/YAF0Inj.png", size: "50x50"), root_path, class: "navbar-brand", style: "margin-left: 5px; padding-top:0px;" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Leaderboard', leaderboard_path %></li>
        <li><%= link_to "My Teams", teams_path %></li>
        <li><%= link_to "Upload Team", new_team_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Profile', edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fanalyst | Daily Fantasy Experts</title>
  <meta content="Learn from and follow the best daily fantasy players" name="description" />
  <meta content="daily fantasy lineups, fantasy sports, best fantasy players" name="keywords" />
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'frontend/favicon.png' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Fanalyst Admin</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'users', admin_users_path %></li> 
            <li><%= link_to 'constants', edit_admin_constant_value_path(ConstantValue.first) %></li>            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
  <div class="container">
    <div class class="row">
      <%= render 'admin/shared/messages' %>
    </div>
    <%= yield %>

  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fanalyst | Daily Fantasy Experts</title>
  <meta content="Learn from and follow the best daily fantasy players" name="description" />
  <meta content="daily fantasy lineups, fantasy sports, best fantasy players" name="keywords" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :js %>
  <%= favicon_link_tag 'images/favicon.png' %>
  <%= csrf_meta_tags %>
 
</head>

<body <%= 'data-no-turbolink' if (controller_name == 'user' && action_name == 'index') %>>
  <div class="container">
    <%= render 'shared/header' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html class="no-js lt-ie9 ie8" lang="en"> <![endif]-->
<!--[if IE 9]> <html class="ie9" lang="en"> <![endif]-->
<!--[if IE 10]> <html class="ie10" lang="en"> <![endif]-->
<!--[if (gt IE 10)|!(IE)]> <html lang="en"> <![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="<%= asset_path('frontend/favicon.png') %>">

  <title>Fanalyst | Home</title>

   <link rel="shortcut icon" href="<%= asset_path('frontend/favicon.png') %>">
 

  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    'frontend', media: 'all' %>

  <%= csrf_meta_tags %>
</head>

<body>

<div class="preloader">
  <div class="spinner">
    <div class="bounce1"></div>
    <div class="bounce2"></div>
    <div class="bounce3"></div>
  </div>
</div>

<!-- NAVBAR
================================================== -->
<div class="navbar-wrapper cbp-af-header">
  <div class="container">

    <!-- Fixed navbar -->
    <div class="navbar cbp-af-inner" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1><a class="navbar-brand scroll" href="#intro">Fanalyst</a></h1>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav pull-right">
           
           
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>

<%= yield %>

<!-- Footer
================================================== -->
<footer id="contact" class="footer">

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="col-sm-3 col-md-3">
          <div class="footer-logo">
            <h2>Fanalyst</h2>
            <p class="muted">2015 Fanalyst</p>
           
          </div>
        </div>
        
        <div class="col-sm-3 col-md-3">
        
          
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 text-center">
        <a class="icon" href="https://twitter.com/fanalystco" target="_blank"><i class="fa fa-twitter"></i></a>
        <a class="icon" href="https://www.facebook.com/fanalystco" target="_blank"><i class="fa fa-facebook"></i></a>
        <a class="icon" href="https://instagram.com/fanalystco/" target="_blank"><i class="fa fa-instagram"></i></a>
     
      </div>
    </div>
  </div>

</footer>

<div id="login" class="overlay overlay-content">

  <button type="button" class="overlay-close">Close</button>
  <section class="login-part">
    <p class="login-overlay">
      Log In
    </p>
    <form method="post">
      <input class="form-control" type="email" name="u" placeholder="Email" required="required" />
      <input class="form-control" type="password" name="p" placeholder="Password" required="required" />
      <button type="submit" class="btn btn-primary btn-block btn-large">Log me in</button>
      <a href="#" class="forgot-pw">Forgot password? We can help!</a>
    </form>
  </section>

</div>

<div id="signup" class="overlay overlay-content">

  <button type="button" class="overlay-close">Close</button>
  <section class="login-part">
    <p class="login-overlay">
      Sign up to Fanalyst
    </p>
    <form method="post">
      <input class="form-control" type="text" name="email" placeholder="Email" required="required" />
      <input class="form-control" type="password" name="pw" placeholder="Password" required="required" />
      <input class="form-control" type="password" name="repeat-pw" placeholder="Repeat Password" required="required" />
      <button type="submit" class="btn btn-primary btn-block btn-large">Get started</button>
      <p class="disclaimer">By signing up, you agree with our <a href="#">Terms of Service</a> & <a href="#">Privacy Policy</a></p>
    </form>
  </section>

</div>

<%= javascript_include_tag 'frontend' %>

<script>

  $(document).ready(function(){
    isotope();
    //signupOverlay();
    //loginOverlay();
  });

</script>

</body>
</html>